version: "3.3"
volumes:
  data:
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: giovane

  app:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'phpmyadmin'
    links:
      - db
    ports:
      - 80:80
